#!/usr/bin/env bash
# seed-hls.sh — Generate HLS media and upload it to MinIO.
#
# Run once after `docker compose up` to seed the Big Buck Bunny title so the
# player works end-to-end. Re-running is idempotent: cached steps are skipped.
#
# PREREQUISITES
#   docker                  (no local ffmpeg, mc, or Node required)
#   docker compose up -d    (minio must be running)
#
# USAGE
#   ./scripts/seed-hls.sh                  # default: synthetic 60s source (no download)
#   BBB_URL=<mp4-url> ./scripts/seed-hls.sh  # use a real MP4 instead
#   DRY_RUN=1 ./scripts/seed-hls.sh          # print plan, do nothing
#
# HOW IT WORKS
#   Step 1  Generate (or download) a source MP4 → .seed-tmp/bbb_source.mp4
#   Step 2  Transcode to 4-rendition HLS ladder (360/480/720/1080p, 4-second
#           segments, independent_segments) via mwader/static-ffmpeg
#   Step 3  Upload to MinIO at hls/{ASSET_ID}/ via minio/mc
#
# The ASSET_ID here must match the row inserted by migration SeedPhase1:
#   20000000-0000-4000-c000-000000000001
#
# CONTENT
#   Default: synthetic test pattern generated by ffmpeg (CC0, no download).
#   With BBB_URL: Big Buck Bunny © 2008 Blender Foundation (CC BY 3.0).
#   See CREDITS.md.

set -euo pipefail

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
ASSET_ID="20000000-0000-4000-c000-000000000001"
S3_KEY="${S3_KEY:-streamflix}"
S3_SECRET="${S3_SECRET:-streamflix_dev_secret}"
S3_BUCKET="${S3_BUCKET:-streamflix-media}"
DOCKER_NETWORK="${DOCKER_NETWORK:-streamflix_default}"
BBB_URL="${BBB_URL:-}"   # empty = generate source locally (default)
DRY_RUN="${DRY_RUN:-0}"

# Work directory inside the repo so Docker Desktop bind-mounts it reliably.
# macOS /tmp is a symlink to /private/tmp — Docker Desktop does not share it.
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKDIR="${REPO_ROOT}/.seed-tmp"
SOURCE_FILE="${WORKDIR}/bbb_source.mp4"
HLS_OUT_DIR="${WORKDIR}/hls/${ASSET_ID}"
MASTER="${HLS_OUT_DIR}/master.m3u8"

# mwader/static-ffmpeg ships native linux/amd64 + linux/arm64 binaries —
# no qemu emulation on Apple Silicon. Use a bash array to avoid word-splitting.
FFMPEG=(docker run --rm -v "${WORKDIR}:/work" mwader/static-ffmpeg)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log() { echo "[seed-hls] $*"; }
die() { echo "[seed-hls] ERROR: $*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker is required"

if [[ "$DRY_RUN" == "1" ]]; then
  log "DRY RUN"
  log "  workdir : ${WORKDIR}"
  log "  network : ${DOCKER_NETWORK}"
  [[ -n "$BBB_URL" ]] \
    && log "  source  : ${BBB_URL}" \
    || log "  source  : ffmpeg-generated (no download)"
  exit 0
fi

mkdir -p "${HLS_OUT_DIR}/360p" "${HLS_OUT_DIR}/480p" \
         "${HLS_OUT_DIR}/720p" "${HLS_OUT_DIR}/1080p"

# ---------------------------------------------------------------------------
# Validate MP4: check the ISO Base Media box type at byte offset 4.
# Returns 0 if the file is a valid MP4/MOV container, 1 otherwise.
# ---------------------------------------------------------------------------
is_valid_mp4() {
  local f="$1"
  [[ -f "$f" ]] || return 1
  local box
  box=$(python3 -c "
import sys
try:
    data = open('$f','rb').read(12)
    print(data[4:8].decode('latin-1', errors='replace'))
except Exception:
    print('')
" 2>/dev/null)
  case "$box" in ftyp|moov|mdat|free|wide|skip) return 0 ;; esac
  return 1
}

# ---------------------------------------------------------------------------
# Step 1 — Source MP4
# ---------------------------------------------------------------------------
INPUT_ARGS=(-i /work/bbb_source.mp4)
MAP_ARGS=(-map 0:v -map 0:a)

if [[ -n "$BBB_URL" ]]; then
  if is_valid_mp4 "$SOURCE_FILE"; then
    log "Cached source valid — skipping download."
  else
    [[ -f "$SOURCE_FILE" ]] && { log "Cached source corrupt — deleting."; rm -f "$SOURCE_FILE"; }
    log "Downloading source MP4…"
    curl --fail -L --progress-bar -o "$SOURCE_FILE" "$BBB_URL" \
      || die "Download failed. Check BBB_URL."
    is_valid_mp4 "$SOURCE_FILE" \
      || die "Downloaded file is not a valid MP4 (server may have returned an error page)."
    log "Download OK."
  fi
else
  if is_valid_mp4 "$SOURCE_FILE"; then
    log "Generated source present — skipping generation."
  else
    [[ -f "$SOURCE_FILE" ]] && { log "Stale source — regenerating."; rm -f "$SOURCE_FILE"; }
    log "Generating 60-second synthetic source MP4…"
    "${FFMPEG[@]}" -y \
      -f lavfi -i "testsrc2=duration=60:size=1920x1080:rate=25" \
      -f lavfi -i "sine=frequency=440:duration=60" \
      -map 0:v -map 1:a \
      -c:v libx264 -preset veryfast -crf 20 \
      -c:a aac -b:a 128k \
      /work/bbb_source.mp4 \
      -loglevel warning
    log "Source generated."
  fi
fi

# ---------------------------------------------------------------------------
# Step 2 — Transcode HLS ladder
#   4 renditions × 4-second segments, independent_segments (CORS-safe seeks)
# ---------------------------------------------------------------------------
if [[ -f "$MASTER" ]]; then
  log "HLS package present — skipping transcode."
else
  log "Transcoding HLS ladder (360/480/720/1080p)…"

  for RES in 360 480 720 1080; do
    case $RES in
      360)  W=640;  H=360;  CRF=28; BR=400k;  MBR=500k;  BUF=800k  ;;
      480)  W=854;  H=480;  CRF=26; BR=800k;  MBR=1000k; BUF=1600k ;;
      720)  W=1280; H=720;  CRF=23; BR=1500k; MBR=2000k; BUF=3000k ;;
      1080) W=1920; H=1080; CRF=20; BR=3000k; MBR=4000k; BUF=6000k ;;
    esac
    log "  ${RES}p…"
    "${FFMPEG[@]}" -y \
      "${INPUT_ARGS[@]}" "${MAP_ARGS[@]}" \
      -vf "scale=${W}:${H}:force_original_aspect_ratio=decrease,pad=${W}:${H}:(ow-iw)/2:(oh-ih)/2" \
      -c:v libx264 -preset veryfast -crf "$CRF" -b:v "$BR" -maxrate "$MBR" -bufsize "$BUF" \
      -c:a aac -b:a 96k \
      -hls_time 4 -hls_flags independent_segments \
      -hls_segment_filename "/work/hls/${ASSET_ID}/${RES}p/seg%03d.ts" \
      "/work/hls/${ASSET_ID}/${RES}p/index.m3u8" \
      -loglevel warning
  done

  cat > "$MASTER" <<'MANIFEST'
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=500000,RESOLUTION=640x360,CODECS="avc1.42e01e,mp4a.40.2"
360p/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1000000,RESOLUTION=854x480,CODECS="avc1.42e01e,mp4a.40.2"
480p/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2000000,RESOLUTION=1280x720,CODECS="avc1.64001e,mp4a.40.2"
720p/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=4000000,RESOLUTION=1920x1080,CODECS="avc1.640028,mp4a.40.2"
1080p/index.m3u8
MANIFEST
  log "Transcode complete."
fi

# ---------------------------------------------------------------------------
# Step 3 — Upload to MinIO
#
# Both mc commands run inside ONE container: mc alias set writes to the
# container's local config file, so a second docker run (fresh container)
# would have no aliases. --entrypoint sh lets us chain the two commands.
# ---------------------------------------------------------------------------
log "Uploading to MinIO (network: ${DOCKER_NETWORK})…"
docker run --rm \
  --network "${DOCKER_NETWORK}" \
  -v "${WORKDIR}:/work" \
  --entrypoint sh \
  minio/mc -c "
    mc alias set sflocal 'http://minio:9000' '${S3_KEY}' '${S3_SECRET}' --api S3v4 -q &&
    mc mirror --overwrite /work/hls/${ASSET_ID}/ sflocal/${S3_BUCKET}/hls/${ASSET_ID}/
  "

log ""
log "✓ Done. Open http://localhost:8080, sign in, and play the video."
